image: node:16

stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

pages:
  stage: deploy
  script:
    - cp -r build/* public/
  artifacts:
    paths:
      - public
  only:
    - main
